name: Makefile CI

on:
  push:
    branches: [ compilacion ]
  pull_request:
    branches: [ compilacion ]

jobs:
  build:

    runs-on: ubuntu-latest-20.04
    name: Build on ubuntu-20.04 aarch64

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./configure
      
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
